### ISSUE TITLE
Missing element-ui component packaging

### ISSUE THREAD

**Issue by lintolynn** [Geocld/vite-plugin-importus#2]
Hello, author
        My element-ui is version 2.13.2，vite version is 3.1.0，When packaged with vite, the element-ui **el-input** component is invalidated，And missing styles for some components，For example, the **el-main** component style is missing，There is nothing wrong with the development environment，This problem occurs after packing In a production environment。

1. This is my configuration in vite.config.js
import vitePluginImportus from 'vite-plugin-importus'
plugins: [
      vitePluginImportus([
              {
                  libraryName: 'element-ui',
                  styleLibraryDirectory: "lib/theme-chalk",
                  customName: (name, file) => {
                      return `element-ui/lib/${name}`;
                  },
                  customStyleName: (name, file) => {
                      return `element-ui/lib/theme-chalk/${name}.css`;
                  }
              }
          ]
      )
  ],

2. This is the configuration in my package.json
{
  "name": "my-project",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build --mode production",
    "build:test": "vite build --mode test",
    "preview": "vite preview"
  },
  "resolutions": {
    "bin-wrapper": "npm:bin-wrapper-china"
  },
  "devDependencies": {
    "@vitejs/plugin-legacy": "^2.3.0",
    "autoprefixer": "^10.4.13",
    "rollup-plugin-visualizer": "^5.8.3",
    "sass": "^1.55.0",
    "vite": "^3.1.0",
    "vite-plugin-compression": "^0.5.1",
    "vite-plugin-imagemin": "^0.6.1",
    "vite-plugin-importus": "^1.0.4",
    "vite-plugin-vue2": "^2.0.2"
  },
  "dependencies": {
    "axios": "^1.1.3",
    "element-ui": "^2.13.2",
    "js-cookie": "^3.0.1",
    "lodash-es": "^4.17.21",
    "vue": "2.5.2",
    "vue-router": "3.0.1",
    "vue-template-compiler": "2.5.2",
    "vuex": "3.0.1"
  }
}

3. This is the configuration in my main.js
// ...Introduction of other components
import {Input} from 'element-ui'
Vue.use(Input);

Looking forward to your reply at last. Thank you！

**Comment by Geocld** [comment]
> Hello, author My element-ui is version 2.13.2，vite version is 3.1.0，When packaged with vite, the element-ui **el-input** component is invalidated，And missing styles for some components，For example, the **el-main** component style is missing，There is nothing wrong with the development environment，This problem occurs after packing In a production environment。
> 
> 1. This is my configuration in vite.config.js
>    import vitePluginImportus from 'vite-plugin-importus'
>    plugins: [
>    vitePluginImportus([
>    {
>    libraryName: 'element-ui',
>    styleLibraryDirectory: "lib/theme-chalk",
>    customName: (name, file) => {
>    return `element-ui/lib/${name}`;
>    },
>    customStyleName: (name, file) => {
>    return `element-ui/lib/theme-chalk/${name}.css`;
>    }
>    }
>    ]
>    )
>    ],
> 2. This is the configuration in my package.json
>    {
>    "name": "my-project",
>    "private": true,
>    "version": "0.0.0",
>    "type": "module",
>    "scripts": {
>    "dev": "vite",
>    "build": "vite build --mode production",
>    "build:test": "vite build --mode test",
>    "preview": "vite preview"
>    },
>    "resolutions": {
>    "bin-wrapper": "npm:bin-wrapper-china"
>    },
>    "devDependencies": {
>    "@vitejs/plugin-legacy": "^2.3.0",
>    "autoprefixer": "^10.4.13",
>    "rollup-plugin-visualizer": "^5.8.3",
>    "sass": "^1.55.0",
>    "vite": "^3.1.0",
>    "vite-plugin-compression": "^0.5.1",
>    "vite-plugin-imagemin": "^0.6.1",
>    "vite-plugin-importus": "^1.0.4",
>    "vite-plugin-vue2": "^2.0.2"
>    },
>    "dependencies": {
>    "axios": "^1.1.3",
>    "element-ui": "^2.13.2",
>    "js-cookie": "^3.0.1",
>    "lodash-es": "^4.17.21",
>    "vue": "2.5.2",
>    "vue-router": "3.0.1",
>    "vue-template-compiler": "2.5.2",
>    "vuex": "3.0.1"
>    }
>    }
> 3. This is the configuration in my main.js
>    // ...Introduction of other components
>    import {Input} from 'element-ui'
>    Vue.use(Input);
> 
> Looking forward to your reply at last. Thank you！

Thanks for your feedback! I try using elementui with vite-plugin-importus, but it work well, please view this [demo](https://github.com/Geocld/elementui-issues).

Please make sure if other plugin's problem?
