### ISSUE TITLE
doesn't work for @xxx/antd

### ISSUE THREAD

**Issue by tjx666** [Geocld/vite-plugin-importus#3]
```
// vitePluginImp({
//     libList: [
//         {
//             libName: '@xxx/antd',
//             libDirectory: 'es',
//             style: (name) => `@xxx/antd/es/${name}/style/css.js`,
//         },
//     ],
// }),
// vitePluginImporter({
//     libraryName: '@xxx/antd',
//     libraryDirectory: 'es',
//     style: (name) => `${name}/style/css.js`,
// }),
vitePluginImportus([
    {
        libraryName: '@xxx/antd',
        libraryDirectory: 'es',
        style: 'css',
    },
]),
```

Another two plugin both works, but this plugin doesn't work, it doesn't load css

Version:

<img width="717" alt="image" src="https://user-images.githubusercontent.com/41773861/205104270-cd8c48b2-9b34-457b-9b3c-da2b57c3bd77.png">

**Comment by Geocld** [comment]
` libraryName ` is match your config, see:

https://github.com/Geocld/vite-plugin-importus/blob/main/packages/vite-plugin-importus/src/transform.ts#L44
